# typed: false
# frozen_string_literal: true

# This file was generated by a script. DO NOT EDIT!
class Pcopy < Formula
  desc "Client to interact with a pcopy temporary file host"
  homepage "https://github.com/binwiederhier/pcopy"
  url "https://api.github.com/repos/binwiederhier/pcopy/tarball/v0.6.1"
  version "0.6.1"
  sha256 "09afe2f2fd0c31953e190da3c9bbb847fcc8887dfcc986ab6df9241c857f434f"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      def install
        ldflags = "-s -w -X main.version=#{version} -X main.date=#{time.iso8601}"
        system "go", "build", *std_go_args(ldflags: ldflags)
      end
    end

    if Hardware::CPU.arm?
      def install
        ldflags = "-s -w -X main.version=#{version} -X main.date=#{time.iso8601}"
        system "go", "build", *std_go_args(ldflags: ldflags)
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      def install
        ldflags = "-s -w -X main.version=#{version} -X main.date=#{time.iso8601}"
        system "go", "build", *std_go_args(ldflags: ldflags)
      end
    end

    if Hardware::CPU.intel?
      def install
        ldflags = "-s -w -X main.version=#{version} -X main.date=#{time.iso8601}"
        system "go", "build", *std_go_args(ldflags: ldflags)
      end
    end
  end
end
