name: build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * *"

jobs:
  tap:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew tap
        run: brew tap nwithan8/formulas
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: brew install formula
        run: brew install --formula /Users/runner/work/homebrew-formulas/homebrew-formulas/formula/*.rb
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: brew audit formula
        run: brew audit --formula /Users/runner/work/homebrew-formulas/homebrew-formulas/formula/*.rb
      - name: Workflow keepalive
        uses: gautamkrishnar/keepalive-workflow@master # Creates a dummy commit when the workflow is stale to keep it from being disabled
        with:
          committer_username: nwithan8
          committer_email: nwithan8@users.noreply.github.com